### ISSUE TITLE
[Docs] Post-deployment Hardening Checklist

### ISSUE THREAD

**Issue by ghost** [reactioncommerce/proxy-traefik#11]
Opening this to make a place to jot down some basics for hardening the installation once deployed. Obviously these things are outside the scope of this project but this repo feels a timely place to communicate some basics. Nothing here should be misconstrued as security advice. _Caveat lector._

- [ ] Attempt to connect to your MongoDB using [Compass](https://www.mongodb.com/products/compass) with the connection string `mongodb://api.example.com:27017` (update based on `domain` var). If you're able to access it without authenticating, shell into the droplet and change `ports` key in `/home/reaction/reaction-development-platform/reaction/docker-compose.yml` to `expose`, change the setting value to `"27017"` and restart the API with `make stop-reaction && make start-reaction` for settings to take effect.
- [ ] Navigate a browser to `admin.example.com` (update based on `domain` var) and register a new user to assume the _Owner_ role. Ownership is immediate and no service restarts are required.
- [ ] Enable the BasicAuth middleware for `traefik.domain.example`. [Detailed instructions here](https://habd.as/post/reaction-commerce-getting-started/#harden-the-installation).
- [ ] Review the `.env` files in each of the projects and modify `PLACEHOLDERS` necessary.

Please add additional suggestions below.
